### ISSUE TITLE
handle http exceptions

### ISSUE THREAD

**Issue by joukhar** [CodesFirst/new_version_plus#49]
when user is not connected to internet, it return this error:
`ClientException with SocketException: Failed host lookup: 'play.google.com' (OS Error: No address associated with hostname, errno = 7), uri=https://play.google.com/store/apps/details?id=<PACKAGE_ID>&hl=en_US`

when app is not found it returns: 
`Unhandled Exception: Exception: Invalid response code: 404`

**Comment by LuisGMM** [comment]
Hello there, similar problem here.

In my case the app is not yet public, so there is an unhandled 404 error when trying to find the app on the Play Store:

```
E/flutter ( 4345): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Invalid response code: 404
E/flutter ( 4345): #0      NewVersionPlus._getAndroidStoreVersion (package:new_version_plus/new_version_plus.dart:191:7)
E/flutter ( 4345): <asynchronous suspension>
E/flutter ( 4345): #1      _ScreenState.checkUpdates (package:app/presentation/ui/screen/screen.dart:56:9)
E/flutter ( 4345): <asynchronous suspension>
```


@pewiher , is there any way to handle these errors?
